config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :sales_representatives
  devise_for :users

        get 'video_search' => 'videos#navbar_search'


        get '/watch/grid/:category_id' => 'videos#full_grid', as: 'full_grid'

        get '/grid/:id' => 'videos#grid'

        get '/watch/live/:channel_slug' => 'videos#watch_channel', as: 'watch_channel'

        get '/watch/movies/:movie_slug' => 'videos#watch_movie', as: 'watch_movie'

        get '/watch/shows/:show_slug' => 'videos#browse_episodes', as: 'browse_episodes'
        # All or page


        get '/watch/shows/:show_slug/:episode_number' => 'videos#watch_episode', as: 'watch_episode'

        post 'remote_sign_in_for_video' => 'videos#remote_sign_in_for_video'
        post 'remote_sign_in' => 'users#remote_sign_in'

        get 'subscribe_newsletter_footer' => 'users#subscribe_newsletter_footer'

        get 'grid_view' => 'videos#grid_view'
        get '/site/500' => 'site#part', as: 'inactive'
  	# User Methods
    authenticate :user do
        get 'update_show_time' => 'time#update_show'
        get 'mark_episode_complete' => 'time#mark_episode_complete'
        get 'mark_show_complete' => 'time#mark_show_complete'

        get 'submit_broken_link' => 'videos#submit_broken_link'


        get 'update_movie_time' => 'time#update_movie'
        get 'mark_movie_complete' => 'time#mark_movie_complete'


  	  	get 'account' => 'users#account'

        get '/account/devices' => 'users#devices', as: 'my_devices'
        get '/account/billing' => 'users#billing', as: 'my_billing'
        get '/account/support' => 'users#support', as: 'my_support'

        get '/account/new_ticket' => 'users#new_ticket', as: 'user_new_ticket'
        post 'user_create_ticket' => 'support#user_create_ticket'
        get 'user_view_ticket' => 'support#user_view_ticket'
        post 'user_send_message_on_ticket' => 'support#user_send_message'
        post 'user_attach_file_to_ticket' => 'support#user_attach_file'

        get 'view_device/:id' => 'users#view_device', as: 'view_device'
        post 'update_roku' => 'users#update_roku'
        post 'update_device' => 'users#update_device'
        post 'register_new_device' => 'users#register_new_device'
        get 'unlink_device' => 'users#unlink_device'

        post 'update_profile' => 'users#update_profile'

        get 'subscribe' => 'users#subscribe'
        get 'view_plan' => 'users#view_plan'
        post 'add_subscription' => "users#add_subscription"

        get '/account/settings' => 'users#settings', as: 'user_settings'
        post 'user_reset_password' => 'users#reset_password'
        get 'user_subscribe_to_mailchimp' => 'users#subscribe_to_mailchimp'
        get 'user_unsubscribe_from_mailchimp' => 'users#unsubscribe_from_mailchimp'

        get 'start_free_trial' => 'users#start_free_trial'

    end

  	# Admin Methods
    authenticate :admin do
        get '/admins/expiry_report' => 'admins#expiry_report', as: 'expiry_report'
        get '/admins/pdf_expiry_report' => 'admins#pdf_expiry_report', as: 'pdf_expiry_report'


        get 'admin_load_devices' => 'admins#load_devices'

        get 'delete_user' => 'admins#delete_user'
        get 'delete_rep' => 'admins#delete_rep'

        post 'create_client_upload' => 'admins#upload_customers'

        get '/admins/migrations/vod/new' => 'vod_migrations#new_vod_upload', as: 'new_vod_upload'
        post 'start_vod_upload' => 'vod_migrations#start_upload'
        get '/admins/migrations/vod' => 'admins#vod_uploads', as: 'vod_uploads'
        get '/admins/migrations/vod/:id' => 'admins#view_vod_upload', as: 'view_vod_upload'

        get '/admins/migrations/client/new' => 'admins#new_client_upload', as: 'new_client_upload'
        post 'start_client_upload' => 'client_migrations#start_upload'
        get '/admins/migrations/client' => 'admins#client_uploads', as: 'client_uploads'
        get '/admins/migrations/client/:id' => 'admins#view_client_upload', as: 'view_client_upload'


        get 'admin_show_existing_grids' => 'admins#show_existing_grids'
        get 'show_sub_expiry' => 'admins#show_sub_expiry'

        mount ResqueWeb::Engine => "/resque_web"
        get '/admins/notifications/view/:id' => 'admin_notifications#notification_redirect', as: 'admin_view_notification'
        get 'clear_notifs' => 'admin_notifications#clear'

  	  	get '/admins' => 'admins#index', as: 'admins'

        get 'admin_view_client_reg_report' => 'admins#view_client_reg_report'
        get 'admin_view_orders_report' => 'admins#view_orders_report'
        get 'admin_view_support_report' => 'admins#view_support_report'

        # General Settings
        get '/admins/settings' => 'admins#general_settings', as: 'general_settings'

        get '/admins/settings/timezone' => 'admins#edit_timezone', as: 'edit_timezone'
        post 'update_default_timezone' => 'admins#update_default_timezone'

        get '/admins/settings/languages' => 'admins#edit_languages', as: 'edit_languages'
        post 'update_languages' => 'admins#update_languages'

        get '/admins/settings/registration_sign_in' => 'admins#edit_registration', as: 'edit_registration'
        post 'update_registration' => 'admins#update_registration'

        get '/admins/settings/payouts' => 'admins#edit_payouts', as: 'edit_payouts'
        post 'update_payout_methods' => 'admins#update_payout_methods'

        get '/admins/settings/device_limit' => 'admins#edit_device_limit', as: 'edit_device_limit'
        post 'update_device_limit' => 'admins#update_device_limit'

        get '/admins/settings/free_trial' => 'admins#edit_free_trial', as: 'edit_free_trial'
        post 'update_free_trial' => 'admins#update_free_trial'

        get '/admins/settings/contact_email' => 'admins#edit_contact_email', as: 'edit_contact_email'
        post 'update_contact_email' => 'admins#update_contact_email'

        get '/admins/settings/wd_limits' => 'admins#edit_wd_limits', as: 'edit_wd_limits'
        post 'update_lower_wd_limit' => 'admins#update_lower_wd_limit'
        post 'update_upper_wd_limit' => 'admins#update_upper_wd_limit'

        get '/admins/settings/footer' => 'admins#edit_footer_content', as: 'edit_footer_content'
        post 'update_footer_content' => 'admins#update_footer_content'


  		# Manage Users
  		get '/admins/users' => 'admins#users', as: 'search_users'
        get '/admins/users/all' => 'admins#all_users', as: 'all_users'
        get 'admin_search_users_table' => 'admins#search_users_table'
  		get 'side_search_users' => 'admins#search_users'
        get '/admins/users/profile/:id' => 'admins#view_user', as: 'view_user'
        get '/admins/users/transactions/:id' => 'admins#view_user_transactions', as: 'view_user_transactions'
        get '/admins/users/devices/:id' => 'admins#view_user_devices', as: 'view_user_devices'
        get '/admins/users/notes/:id' => 'admins#view_user_notes', as: 'view_user_notes'
        get '/admins/users/subscription_adjustment/:id' => 'admins#view_user_subscription', as: 'view_user_subscription'
        get '/admins/users/balance_adjustment/:id' => 'admins#view_user_balance', as: 'view_user_balance'

        get 'reset_user_password' => 'admins#reset_user_password'
        post 'manual_reset_user_password' => 'admins#manual_reset_user_password'

        post 'update_user_roku_account' => 'admins#update_user_roku_account'
        post 'update_user_language' => 'admins#update_user_language'

        post 'admin_update_user_profile' => 'admins#update_user_profile'
        post 'admin_update_user_mailing' => 'admins#update_user_mailing'
        post 'extend_user_subscription' => 'admins#extend_user_subscription'
        get 'cancel_user_subscription' => 'admins#cancel_user_subscription'
        post 'update_user_balance' => 'admins#update_user_balance'
        post 'admin_create_transaction' => 'admins#create_transaction'
        post 'admin_register_device' => 'admins#register_device'
        get 'admin_unlink_device' => 'admins#unlink_device'
        get 'admin_toggle_user_status' => 'admins#toggle_user_status'

        post 'add_note_to_user' => 'users#add_note'
        post 'add_image_to_note' => 'users#add_image_to_note'
        post 'update_note' => 'users#update_note'
        post 'add_image_to_existing_note' => 'users#add_image_to_existing_note'
        get 'delete_note_file' => 'users#delete_note_file'
        get 'delete_note' => 'users#delete_note'
        get 'delete_unsaved_note' => 'users#delete_unsaved_note'

        get 'admin_choose_plan' => 'admins#choose_plan'
        post 'admin_add_subscription' => 'admins#add_subscription'
        post 'admin_add_subscription_user' => 'admins#add_subscription_user'

  		get '/admins/new_user' => 'admins#new_user', as: 'new_user'
  		post 'admin_create_user' => 'admins#create_user'

        get '/admins/users/pending_payments' => 'admins#user_payment_queue'

        # Transactions
        get '/admins/orders' => 'admins#orders', as: 'orders'
        get '/admins/orders/new' => 'admins#new_transaction', as: 'new_tx'
        post 'admin_create_transaction' => 'admins#create_transaction'
        get '/admins/orders/pending' => 'admins#pending_transactions', as: 'pending_tx'
        get '/admins/orders/paid' => 'admins#paid_transactions', as: 'paid_tx'
        get '/admins/orders/refunded' => 'admins#refunded_transactions', as: 'refunded_tx'
        get '/admins/orders/cancelled' => 'admins#cancelled_transactions', as: 'cancelled_tx'
        get '/admins/orders/view/:id' => 'transactions#show', as: 'view_tx'
        post 'update_transaction_dates' => 'transactions#update_dates'

        post 'create_tx_standalone' => 'transactions#create_standalone'

        post 'create_tx_user' => 'transactions#create_user'

        get 'accept_payment' => 'transactions#accept'
        get 'cancel_payment' => 'transactions#cancel'
        get 'refund_payment' => 'transactions#refund'

  		# Video CMS

app/views/admins/create_grid.js.erb
$('#name-error').remove()
$('#weight-error').remove()

<% if @grid.errors.any? %>
	alert('<%= @grid.errors.full_messages.join(" | ") %>')
    <% if @grid.errors[:name].any? %>
        $('#name').after('<div class="text-danger" id="name-error">Name <%= @grid.errors[:name].join(", ") %></div>')
    <% end %>
    <% if @grid.errors[:weight].any? %>
        $('#weight').after('<div class="text-danger" id="weight-error">Sort weight <%= @grid.errors[:weight].join(", ") %></div>')
    <% end %>
<% else %>
    window.location = '<%= admin_view_grid_path(id: @grid.id) %>'
<% end %>

app/views/admins/edit_timezone.html.erb
<% content_for :top_level, 'Utilities' %>
<% content_for :low_levels, YAML.dump(['General Settings','Time Zone']) %>


<% map = ActiveSupport::TimeZone.all %>
<% array = Array.new %>
<% map.each do |tz| %>
    <% array.push(tz.to_s) %>
<% end %>

<% tz_options = [['Select A Timezone',nil]] %>

<% array.each do |tz_s| %>
    <% tz_s.slice!(0..11) %>
    <% tz_options.push(tz_s) unless tz_s.nil? %>
<% end %>
<div id="left-scroll" class="nano">
    <div class="nano-content">
        <div class='col-md-6 col-sm-9 col-centered'>
            <div class='row'>
                <div class='col-sm-12'>
                    <div class='panel panel-default'>
                        <div class='panel-heading'>
                            <h3 class='panel-title'>Current Timezone</h3>
                        </div>
                        <div class='panel-body text-center', style='font-size: 180%'>
                            <%= @current_zone %>
                        </div>
                    </div>
                    <%= form_tag update_default_timezone_path do %>
                    <div class='panel panel-default'>
                        <div class='panel-heading'>
                            <h3 class='panel-title'>Set New Default</h3>
                        </div>
                        <div class='panel-body text-center', style='font-size: 180%'>
                            <%= select_tag :timezone, options_for_select(tz_options, @current_zone), class: 'form-control' %>
                        </div>
                        <div class='panel-footer'>
                            <%= submit_tag 'Update', class: 'btn btn-primary', style: 'width: 100%' %>
                        </div>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#timezone_side').addClass('active')
</script>

app/views/admins/expiry_report.html.erb
<% content_for :top_level, 'Dashboard' %>
<% content_for :low_levels, YAML.dump(['Expiry Report']) %>
<div id="left-scroll" class="nano">
    <div class="nano-content">
        <%= form_tag pdf_expiry_report_path(range: params[:range]), method: :get do %>
        <div class="panel">
            <div class="panel-heading ptb5">
                <div class="row">
                    <div class="col-md-3">
                        <div class="mt5"><span class="icon-graph mr7"></span> Reports <a href="#" class="sign"><span class="fa fa-question-circle"></span></a></div>
                    </div>
                    <div class="col-md-9 text-right">
                        <%= submit_tag 'PRINT',  class: "btn btn-default btn-sm btn-w170" %>
                        <%= link_to '30 Days', '#', style: 'cursor:pointer', class: "btn btn-default btn-sm btn-w170", id: '30_days', onclick: 'window.location= "'+expiry_report_path(range: 30)+'"' %>
                        <%= link_to '14 Days', '#', style: 'cursor:pointer', class: "btn btn-default btn-sm btn-w170", id: '14_days', onclick: 'window.location= "'+expiry_report_path(range: 14)+'"' %>
                        <%= link_to '7 Days', '#', style: 'cursor:pointer', class: "btn btn-default btn-sm btn-w170", id: '7_days', onclick: 'window.location= "'+expiry_report_path(range: 7)+'"' %>
                        <%= link_to 'Today', '#', style: 'cursor:pointer', class: "btn btn-default btn-sm btn-w170", id: '0_days', onclick: 'window.location= "'+expiry_report_path(range: 0)+'"' %>
                    </div>
                </div>
            </div>
            <div class="panel-body" id='reports'>
                <table class='table fz12-5 table-nb1'>
                    <thead><tr>
                        <th><a style="cursor:pointer" onclick='selectAll()' id='select_all'>Select All</a>
                            <a style="cursor:pointer; display:none" onclick='deselectAll()' id='deselect_all'>Deselect All</a></th>
                        <th>Name</th>
                        <th>Sub Type</th>
                        <th>Expiry</th>
                        <th>Current Plan</th>
                        <th>Last Printed</th>
                    </tr></thead>
                    <% @expirations.each do |ex| %>
                        <% if ex[:type] == 'Web' %>
                            <% user = User.find(ex[:id]) %>
                            <% tx = Transaction.where(id: ex[:last_tx]).first %>
                        <% else %>
                            <% roku = Roku.find(ex[:id]) %>
                            <% user = User.find(roku.user_id) %>
                            <% tx = Transaction.where(id: ex[:last_tx]).first %>
                        <% end %>

                        <tr>
                            <% if ex[:type] == 'Web' %>
                                <td>
                                    <%= check_box_tag 'users[]', user.id, false, class: 'check-group' %>
                                </td>
                            <% else %>
                                <td>
                                    <%= check_box_tag 'rokus[]', roku.id, false, class: 'check-group' %>
                                </td>
                            <% end %>
                            <td><%= link_to user.name, view_user_path(id: user.id) %></td>
                            <td><%= ex[:type] %></td>
                            <% if ex[:type] == 'Web' %>
                                <td><%= user.expiry.strftime('%B %-d, %Y') %></td>
                            <% else %>
                                <td><%= roku.expiry.strftime('%B %-d, %Y') %></td>
                            <% end %>
                            <% if tx.nil? %>
                                <% if ex[:type] == 'Web' %>
                                    <td>FREE TRIAL - (WEB/TABLET/MOBILE)</td>
                                <% else %>
                                    <td>FREE TRIAL - (<%= roku.serial %>)</td>
                                <% end %>
                            <% else %>
                                <% if ex[:type] == 'Web' %>
                                    <% tx_details = YAML.load(tx.product_details) %>
                                    <td><%= tx_details[:name].upcase %></td>
                                <% else %>
                                    <% tx_details = YAML.load(tx.product_details) %>
                                    <td><%= tx_details[:name].upcase %></td>
                                <% end %>
                            <% end %>
                            <% if ex[:type] == 'Web' %>
                                <% if user.last_printed.nil? %>
                                    <td>Never</td>
                                <% else %>
                                    <td><%= user.last_printed.strftime('%B %-d, %Y at %H:%M') %></td>
                                <% end %>
                            <% else %>
                                <% if roku.last_printed.nil? %>
                                    <td>Never</td>
                                <% else %>
                                    <td><%= roku.last_printed.strftime('%B %-d, %Y at %H:%M') %></td>
                                <% end %>
                            <% end %>
                        </tr>
                    <% end %>
                </table>
            </div>
        </div>
        <% end %>
    </div>
</div>
<script type="text/javascript">
    $.ajax({
        url: '/load_activity_feed'
    })
    function load_updates(timestamp){
        $('#loading').html()
        $.ajax({
            url: '/load_activity_feed?before='+timestamp
        })
    }
    $(window).resize(function(){
        waitForFinalEvent(function(){
            chart.redraw()
        },500,makeid())
    })
    var waitForFinalEvent = (function () {
        var timers = {};
        return function (callback, ms, uniqueId) {
            if (!uniqueId) {
                uniqueId = "Don't call this twice without a uniqueId";
            }
            if (timers[uniqueId]) {
                clearTimeout (timers[uniqueId]);
            }
            timers[uniqueId] = setTimeout(callback, ms);
        };
    })();
    function makeid() {
        var text = "";
        var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

        for( var i=0; i < 5; i++ )
            text += possible.charAt(Math.floor(Math.random() * possible.length));

        return text;
    }

    function selectAll(){
        $('#select_all').hide()
        $('#deselect_all').show()
        $('.check-group').each(function(){
            this.checked = true
        })
    }

    function deselectAll(){
        $('#select_all').show()
        $('#deselect_all').hide()
        $('.check-group').each(function(){
            this.checked = false
        })
    }

    <% if params[:range].present? %>
        $('#<%= params[:range] %>_days').addClass('active')
    <% else %>
        $('#0_days').addClass('active')
    <% end %>
    $('#expiry_report').addClass('active')
</script>

app/views/admins/search_users_for_ticket_order.js.erb
$('#user_row').html('')
<% if @matched_users.any? %>
    <% @matched_users.each do |user| %>
        <% @user = user %>
        <% if params[:search_type] == 'user' %>
            $('#user_row').append('<%= escape_javascript(render("support/partials/user_search_item")) %>')
        <% else %>
            $('#user_row').append('<%= escape_javascript(render("support/partials/rep_search_item")) %>')
        <% end %>
    <% end %>
<% else %>
    $('#user_row').html('<div class="col-sm-6 col-md-3 col-lg-2 active_user user_wrapper"><div class="panel-bordered text-center"><div class="panel-bordered-header">No clients found</div></div></div>')
<% end %>

app/views/admins/search_users_table.js.erb
$('#user_table').html('')
<% @matched_users.each do |user| %>
    <% @user = user %>
    $('#user_table').append('<%= escape_javascript(render("admins/partials/user_table_item")).html_safe %>')
<% end %>

app/views/admins/update_mailchimp.js.erb
<% if @success == true %>
    addNotification('success', '<%= @message %>', 'Success', 'check-circle')
<% else %>
    addNotification('error', '<%= @message %>', 'Error', 'exclamation-circle')
<% end %>

app/views/admins/update_user_balance.js.erb
<% if @user.errors.any? %>
    addNotification('error', 'There was an error saving the balance', 'Error', 'exclamation-circle')
<% else %>
    $('#user_balance').html('$<%= number_with_precision(@user.balance, precision: 2) %>')
    $('#balance_2').html('$<%= number_with_precision(@user.balance, precision: 2) %>')
    addNotification('success', 'Balance updated', 'Success', 'check-circle')
    $('#add_balance').val('')
    $('#tx_details').html("<div class='stat-number'><div class='number'><i class='fa fa-refresh fa-spin'></i></div>Loading Details</div>")

    $.ajax({
        url: '/admin_choose_plan?user_id=<%= @user.id %>&plan_id='+$('#plan_id').val()+'&roku_id='+$('#tx_serial').val()
    })
<% end %>

app/views/admins/view_device.js.erb
$('#serial_message').remove()
$('#device_name').val('<%= @device.name %>')
<% if @device.adult.nil? %>
    $('#device_adult').val('false')
<% else %>
    $('#device_adult').val('<%= @device.adult %>')
<% end %>
$('#device_id').val(<%= @device.id %>)
$('#device_image').attr('src','/assets/<%= @device.type.downcase %>_large.png')
$('#device_modal').modal('show')
$('#device_type').html('<%= @device.humanized_type %>')
$('#device_active').val('<%= @device.is_active %>')
$('#device_linked').html('<%= @device.created_at.strftime('%B %-d, %Y') %>')
<% if @device.type == 'Roku' %>
    $('#device_status').html('<%= @device.status %>')
    $('#device_serial').val('<%= @device.serial %>')
    $('#serial_wrapper').show()
<% else %>
    $('#device_status').html('N/A')
    $('#device_serial').val('N/A')
    $('#serial_wrapper').hide()
<% end %>
$('#unlink_btn').html('<%= link_to "Unlink Device", admin_unlink_device_path(id: @device.id), remote: true, class: "btn btn-danger", style: "width: 100%", data: {confirm: "Are you sure you want to delete this device?"} %>')
<% if @device.name.present? %>
    $('#device-modal-title').html('Edit <%= @device.nickname(true) %>')
<% else %>
    $('#device-modal-title').html('Edit <%= @device.humanized_type %>')
<% end %>
<% if @device.type == 'Roku' %>
    $('#device_dates').show()
    <% if @device.start_date.nil? %>
        $('#device_start_month').val(<%= Date.today.strftime('%m').to_i %>)
        $('#device_start_day').val(<%= Date.today.strftime('%d').to_i %>)
        $('#device_start_year').val(<%= Date.today.strftime('%Y').to_i %>)
    <% else %>
        $('#device_start_month').val(<%= @device.start_date.strftime('%m').to_i %>)
        $('#device_start_day').val(<%= @device.start_date.strftime('%d').to_i %>)
        $('#device_start_year').val(<%= @device.start_date.strftime('%Y').to_i %>)
    <% end %>

    <% if @device.expiry.nil? %>
        $('#device_expiry_month').val(<%= Date.today.strftime('%m').to_i %>)
        $('#device_expiry_day').val(<%= Date.today.strftime('%d').to_i %>)
        $('#device_expiry_year').val(<%= Date.today.strftime('%Y').to_i %>)
    <% else %>
        $('#device_expiry_month').val(<%= @device.expiry.strftime('%m').to_i %>)
        $('#device_expiry_day').val(<%= @device.expiry.strftime('%d').to_i %>)
        $('#device_expiry_year').val(<%= @device.expiry.strftime('%Y').to_i %>)
    <% end %>
<% else %>
    $('#device_dates').hide()
<% end %>

app/views/admins/view_request.js.erb
$('#request_details').html('<%= escape_javascript(render("admins/partials/request_details")) %>')

app/views/admins/view_user_notes.html.erb
<% content_for :top_level, 'Clients' %>
<% content_for :low_levels, YAML.dump([@user.name, 'Notes']) %>
<div id="left-scroll" class="nano">
    <div class="nano-content">
        <div class='row'>
            <div class='col-xs-12'>
                <div class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <div class="number" id='user_balance'>$<%= number_with_precision(@user.balance, precision: 2) %></div>
                                    Account Balance
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <div class="number" id='pending_tx'>$<%= number_with_precision(@pending, precision: 2) %></div>
                                    Pending Payments
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <div class="number"><%= @devices.count %></div>
                                    Devices
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <div class="number" id='membership_1'><% if @user.expiry.nil? || @user.expiry < Date.today %>Free<% else %>Premium<% end %></div>
                                    Membership
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-6 col-sm-8 '>
                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        <h3 class='panel-title'>New Note</h3>
                    </div>
                    <div class='panel-body'>
                        <%= form_tag add_note_to_user_path, remote: true do %>
                            <%= hidden_field_tag :user_id, @user.id %>
                            <div class="form-editor expand bgcolor-1" id='note_form' style=' margin-bottom: 10px'>
                                <%= text_field_tag :note_title, '', class: 'form-control input-md input-title', placeholder: 'Title' %>
                                <%= text_area_tag :note, '', class: 'form-control', placeholder: 'Add a note...' %>
                                <div class='' id='note-reglist' style='display:none; margin-bottom: 3px'></div>
                                <div class='' id='note-checklist' style='display:none; margin-bottom: 3px'></div>
                                <div class="icon-editor">
                                    <div class="row">
                                        <%= hidden_field_tag :color, nil %>
                                        <div class="col-sm-6">
                                            <div class="btn-group">
                                                <button type="button" class="btn-icon" data-toggle="dropdown"><span class="fa fa-square-o"></span></button>
                                                <div class="dropdown-menu dropdown-border" role="menu" id='color-picker'>
                                                    <a id='bgcolor-1' class="sqcolor-1 selected"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-2' class="sqcolor-2"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-3' class="sqcolor-3"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-4' class="sqcolor-4"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-5' class="sqcolor-5"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-6' class="sqcolor-6"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-7' class="sqcolor-7"><span class="fa fa-check"></span></a>
                                                    <a id='bgcolor-8' class="sqcolor-8"><span class="fa fa-check"></span></a>
                                                </div>
                                            </div>
                                            <button type="button" onclick='addChecklistNew()' class='btn btn-icon'><i class='fa fa-check-square-o'></i></button>
                                            <button type="button" onclick='addReglistNew()' class='btn btn-icon'><i class='fa fa-list'></i></button>
                                        </div>
                                        <div class="col-sm-6 text-right save">
                                            <div class="fz12-5" id='save_btn'><%= submit_tag 'Save Note', class: 'btn btn-icon', data: {disable_with: 'Saving...'} %></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>

                <div class='panel panel-default'>
                    <div class='panel-heading'>
                        <h3 class='panel-title'>Client Notes</h3>
                    </div>
                    <div class='panel-body'>
                        <div id='notes_list'>
                            <% @notes.each do |note| %>
                                <% @note = note %>
                                <%= render 'users/partials/note' %>
                            <% end %>
                        </div>
                    </div>
                </div>
                <script>
                    function addChecklistNew(){
                        $('#note-checklist').show()
                        $('#note-checklist').append('<%= escape_javascript(render("users/partials/checklist_item")) %>')
                    }
                    function addReglistNew(){
                        $('#note-reglist').show()
                        $('#note-reglist').append('<%= escape_javascript(render("users/partials/reglist_item")) %>')
                    }

                </script>
            </div>
        </div>
    </div>
</div>
<script>
$('#user_notes').addClass('active')
var current_uploaded_image = 0
function viewDevice(id) {
    $.ajax({
        url: '/admin_view_device/'+id
    })
}
function deleteImage(id){
    $.ajax({
        url: '/delete_note_file?id='+id
    })
}
$(window).bind('beforeunload', function(){
    $.ajax({
        url: '/delete_unsaved_note?id='+$('#new_note_id').val()
    })
});
$('#color-picker a').click(function(){
    $('#color-picker a').removeClass('selected')
    $(this).addClass('selected')
    $('#note_form').removeClass('bgcolor-8 bgcolor-7 bgcolor-6 bgcolor-5 bgcolor-4 bgcolor-3 bgcolor-2 bgcolor-1')
    $('#note_form').addClass($(this).attr('id'))
    $('#color').val($(this).attr('id'))
})
</script>