config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :sales_representatives
  devise_for :users

        get 'video_search' => 'videos#navbar_search'


        get '/watch/grid/:category_id' => 'videos#full_grid', as: 'full_grid'

        get '/grid/:id' => 'videos#grid'

        get '/watch/live/:channel_slug' => 'videos#watch_channel', as: 'watch_channel'

        get '/watch/movies/:movie_slug' => 'videos#watch_movie', as: 'watch_movie'

        get '/watch/shows/:show_slug' => 'videos#browse_episodes', as: 'browse_episodes'
        # All or page


        get '/watch/shows/:show_slug/:episode_number' => 'videos#watch_episode', as: 'watch_episode'

        post 'remote_sign_in_for_video' => 'videos#remote_sign_in_for_video'
        post 'remote_sign_in' => 'users#remote_sign_in'

        get 'subscribe_newsletter_footer' => 'users#subscribe_newsletter_footer'

        get 'grid_view' => 'videos#grid_view'
        get '/site/500' => 'site#part', as: 'inactive'
  	# User Methods
    authenticate :user do
        get 'update_show_time' => 'time#update_show'
        get 'mark_episode_complete' => 'time#mark_episode_complete'
        get 'mark_show_complete' => 'time#mark_show_complete'

        get 'submit_broken_link' => 'videos#submit_broken_link'


        get 'update_movie_time' => 'time#update_movie'
        get 'mark_movie_complete' => 'time#mark_movie_complete'


  	  	get 'account' => 'users#account'

        get '/account/devices' => 'users#devices', as: 'my_devices'
        get '/account/billing' => 'users#billing', as: 'my_billing'
        get '/account/support' => 'users#support', as: 'my_support'

        get '/account/new_ticket' => 'users#new_ticket', as: 'user_new_ticket'
        post 'user_create_ticket' => 'support#user_create_ticket'
        get 'user_view_ticket' => 'support#user_view_ticket'
        post 'user_send_message_on_ticket' => 'support#user_send_message'
        post 'user_attach_file_to_ticket' => 'support#user_attach_file'

        get 'view_device/:id' => 'users#view_device', as: 'view_device'
        post 'update_roku' => 'users#update_roku'
        post 'update_device' => 'users#update_device'
        post 'register_new_device' => 'users#register_new_device'
        get 'unlink_device' => 'users#unlink_device'

        post 'update_profile' => 'users#update_profile'

        get 'subscribe' => 'users#subscribe'
        get 'view_plan' => 'users#view_plan'
        post 'add_subscription' => "users#add_subscription"

        get '/account/settings' => 'users#settings', as: 'user_settings'
        post 'user_reset_password' => 'users#reset_password'
        get 'user_subscribe_to_mailchimp' => 'users#subscribe_to_mailchimp'
        get 'user_unsubscribe_from_mailchimp' => 'users#unsubscribe_from_mailchimp'

        get 'start_free_trial' => 'users#start_free_trial'

    end

  	# Admin Methods
    authenticate :admin do
        get '/admins/expiry_report' => 'admins#expiry_report', as: 'expiry_report'
        get '/admins/pdf_expiry_report' => 'admins#pdf_expiry_report', as: 'pdf_expiry_report'


        get 'admin_load_devices' => 'admins#load_devices'

        get 'delete_user' => 'admins#delete_user'
        get 'delete_rep' => 'admins#delete_rep'

        post 'create_client_upload' => 'admins#upload_customers'

        get '/admins/migrations/vod/new' => 'vod_migrations#new_vod_upload', as: 'new_vod_upload'
        post 'start_vod_upload' => 'vod_migrations#start_upload'
        get '/admins/migrations/vod' => 'admins#vod_uploads', as: 'vod_uploads'
        get '/admins/migrations/vod/:id' => 'admins#view_vod_upload', as: 'view_vod_upload'

        get '/admins/migrations/client/new' => 'admins#new_client_upload', as: 'new_client_upload'
        post 'start_client_upload' => 'client_migrations#start_upload'
        get '/admins/migrations/client' => 'admins#client_uploads', as: 'client_uploads'
        get '/admins/migrations/client/:id' => 'admins#view_client_upload', as: 'view_client_upload'


        get 'admin_show_existing_grids' => 'admins#show_existing_grids'
        get 'show_sub_expiry' => 'admins#show_sub_expiry'

        mount ResqueWeb::Engine => "/resque_web"
        get '/admins/notifications/view/:id' => 'admin_notifications#notification_redirect', as: 'admin_view_notification'
        get 'clear_notifs' => 'admin_notifications#clear'

  	  	get '/admins' => 'admins#index', as: 'admins'

        get 'admin_view_client_reg_report' => 'admins#view_client_reg_report'
        get 'admin_view_orders_report' => 'admins#view_orders_report'
        get 'admin_view_support_report' => 'admins#view_support_report'

        # General Settings
        get '/admins/settings' => 'admins#general_settings', as: 'general_settings'

        get '/admins/settings/timezone' => 'admins#edit_timezone', as: 'edit_timezone'
        post 'update_default_timezone' => 'admins#update_default_timezone'

        get '/admins/settings/languages' => 'admins#edit_languages', as: 'edit_languages'
        post 'update_languages' => 'admins#update_languages'

        get '/admins/settings/registration_sign_in' => 'admins#edit_registration', as: 'edit_registration'
        post 'update_registration' => 'admins#update_registration'

        get '/admins/settings/payouts' => 'admins#edit_payouts', as: 'edit_payouts'
        post 'update_payout_methods' => 'admins#update_payout_methods'

        get '/admins/settings/device_limit' => 'admins#edit_device_limit', as: 'edit_device_limit'
        post 'update_device_limit' => 'admins#update_device_limit'

        get '/admins/settings/free_trial' => 'admins#edit_free_trial', as: 'edit_free_trial'
        post 'update_free_trial' => 'admins#update_free_trial'

        get '/admins/settings/contact_email' => 'admins#edit_contact_email', as: 'edit_contact_email'
        post 'update_contact_email' => 'admins#update_contact_email'

        get '/admins/settings/wd_limits' => 'admins#edit_wd_limits', as: 'edit_wd_limits'
        post 'update_lower_wd_limit' => 'admins#update_lower_wd_limit'
        post 'update_upper_wd_limit' => 'admins#update_upper_wd_limit'

        get '/admins/settings/footer' => 'admins#edit_footer_content', as: 'edit_footer_content'
        post 'update_footer_content' => 'admins#update_footer_content'


  		# Manage Users
  		get '/admins/users' => 'admins#users', as: 'search_users'
        get '/admins/users/all' => 'admins#all_users', as: 'all_users'
        get 'admin_search_users_table' => 'admins#search_users_table'
  		get 'side_search_users' => 'admins#search_users'
        get '/admins/users/profile/:id' => 'admins#view_user', as: 'view_user'
        get '/admins/users/transactions/:id' => 'admins#view_user_transactions', as: 'view_user_transactions'
        get '/admins/users/devices/:id' => 'admins#view_user_devices', as: 'view_user_devices'
        get '/admins/users/notes/:id' => 'admins#view_user_notes', as: 'view_user_notes'
        get '/admins/users/subscription_adjustment/:id' => 'admins#view_user_subscription', as: 'view_user_subscription'
        get '/admins/users/balance_adjustment/:id' => 'admins#view_user_balance', as: 'view_user_balance'

        get 'reset_user_password' => 'admins#reset_user_password'
        post 'manual_reset_user_password' => 'admins#manual_reset_user_password'

        post 'update_user_roku_account' => 'admins#update_user_roku_account'
        post 'update_user_language' => 'admins#update_user_language'

        post 'admin_update_user_profile' => 'admins#update_user_profile'
        post 'admin_update_user_mailing' => 'admins#update_user_mailing'
        post 'extend_user_subscription' => 'admins#extend_user_subscription'
        get 'cancel_user_subscription' => 'admins#cancel_user_subscription'
        post 'update_user_balance' => 'admins#update_user_balance'
        post 'admin_create_transaction' => 'admins#create_transaction'
        post 'admin_register_device' => 'admins#register_device'
        get 'admin_unlink_device' => 'admins#unlink_device'
        get 'admin_toggle_user_status' => 'admins#toggle_user_status'

        post 'add_note_to_user' => 'users#add_note'
        post 'add_image_to_note' => 'users#add_image_to_note'
        post 'update_note' => 'users#update_note'
        post 'add_image_to_existing_note' => 'users#add_image_to_existing_note'
        get 'delete_note_file' => 'users#delete_note_file'
        get 'delete_note' => 'users#delete_note'
        get 'delete_unsaved_note' => 'users#delete_unsaved_note'

        get 'admin_choose_plan' => 'admins#choose_plan'
        post 'admin_add_subscription' => 'admins#add_subscription'
        post 'admin_add_subscription_user' => 'admins#add_subscription_user'

  		get '/admins/new_user' => 'admins#new_user', as: 'new_user'
  		post 'admin_create_user' => 'admins#create_user'

        get '/admins/users/pending_payments' => 'admins#user_payment_queue'

        # Transactions
        get '/admins/orders' => 'admins#orders', as: 'orders'
        get '/admins/orders/new' => 'admins#new_transaction', as: 'new_tx'
        post 'admin_create_transaction' => 'admins#create_transaction'
        get '/admins/orders/pending' => 'admins#pending_transactions', as: 'pending_tx'
        get '/admins/orders/paid' => 'admins#paid_transactions', as: 'paid_tx'
        get '/admins/orders/refunded' => 'admins#refunded_transactions', as: 'refunded_tx'
        get '/admins/orders/cancelled' => 'admins#cancelled_transactions', as: 'cancelled_tx'
        get '/admins/orders/view/:id' => 'transactions#show', as: 'view_tx'
        post 'update_transaction_dates' => 'transactions#update_dates'

        post 'create_tx_standalone' => 'transactions#create_standalone'

        post 'create_tx_user' => 'transactions#create_user'

        get 'accept_payment' => 'transactions#accept'
        get 'cancel_payment' => 'transactions#cancel'
        get 'refund_payment' => 'transactions#refund'

  		# Video CMS

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/add_grid.js.erb
<% unless @category.errors.any? %>
    window.location = '/admins/videos/home_grid'
<% else %>
    $('#new_name-error').remove()
    $('#new_rank-error').remove()
    $('#new_item_type-error').remove()
    $('#new_free-error').remove()
    <% if @category.errors[:name].present? %>
        $('#new_name').after('<div class="text-danger" id="new_name-error">Name <%= @category.errors[:name].join(", ") %>.</div>')
    <% end %>
    <% if @category.errors[:rank].present? %>
        $('#new_rank').after('<div class="text-danger" id="new_rank-error">Grid number <%= @category.errors[:rank].join(", ") %>.</div>')
    <% end %>
    <% if @category.errors[:item_type].present? %>
        $('#new_item_type').after('<div class="text-danger" id="new_item_type-error">Class filter <%= @category.errors[:item_type].join(", ") %>.</div>')
    <% end %>
    <% if @category.errors[:free].present? %>
        $('#new_free').after('<div class="text-danger" id="new_free-error">Membership <%= @category.errors[:free].join(", ") %>.</div>')
    <% end %>
<% end %>

app/views/videos/channel.html.erb
<div class="content">
        	<div class="container">
            	<div class="row">
                	<div class="col-sm-4 col-md-3">
                    	<div class="panel panel-custom">
                        	<div class="panel-heading">
                            	<h3 class="fz14"><%= @channel.name %></h3>
                            </div>
                            <div class="panel-body b0">
                                <%= image_tag @channel.image_url, class: 'img-responsive' %>
                            </div>
                        </div>
                        <div class="socials">
                        	<a href="#"><span class="fb"></span></a>
                        	<a href="#"><span class="tw"></span></a>
                        	<a href="#"><span class="rss"></span></a>
                        </div>
                    </div>
                    <div class="col-sm-8 col-md-9">
                   		<div class="box-white">
                        	<div class="data-bb clearfix">
                            	<div class="pull-left">
                                    <span class="star-wrap">
                                        <span class="glyphicon glyphicon-star yellow"></span>
                                        <span class="glyphicon glyphicon-star yellow"></span>
                                        <span class="glyphicon glyphicon-star yellow"></span>
                                        <span class="glyphicon glyphicon-star yellow"></span>
                                        <span class="glyphicon glyphicon-star"></span>
                                    </span>
                                    <div class="fz12-5">2013</div>
                                </div>
                                <div class="pull-right">
                                	<br>
                                	<div class="fz12-5">4 Episodes</div>
                                </div>
                            </div>
                            <div class="data-bb">
                        	Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
                            </div>
                            <% @episodes.each do |episode| %>
                            <div class="box-episode clearfix">
                            	<a href="/watch/<%= @channel.id %>/<%= episode.id %>">
                            		<span class="fz12-5"><%= episode.release_date %></span> - Episode <%= episode.episode_number %> - <%= episode.title %>
                                    <i class='fa fa-play-circle-o play-icon'></i>
                                </a>
                            </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--content-->

app/views/videos/delete_grid.js.erb
window.location = '/admins/videos/home_grid'

app/views/videos/delete_movie.js.erb
$('#movie_<%= @id %>').remove()
$('#movie_search_<%= @id %>').remove()
$('#details_wrapper').html('')

app/views/videos/navbar_search.js.erb
<% if @channels.any? || @movies.any? || @shows.any? %>
    $('#search_placeholder').html('<%= @channels.count + @movies.count + @shows.count %> found')
    $('#search_result_list').html('')
    <% @channels.each do |channel| %>
        $('#search_result_list').append('<div class="result" onclick="window.location = \'<%= watch_channel_path(channel_slug: channel.slug) %>\'"><div class="image"><%= image_tag channel.image_url(:preview) %></div><div class="desc"><span class="name"><%= channel.name %></div></div>')
    <% end %>
    <% @movies.each do |movie| %>
        $('#search_result_list').append('<div class="result" onclick="window.location = \'<%= watch_movie_path(movie_slug: movie.slug) %>\'"><div class="image"><%= image_tag movie.image_url(:preview) %></div><div class="desc"><span class="name"><%= movie.name %></div></div>')
    <% end %>
    <% @shows.each do |show| %>
        $('#search_result_list').append('<div class="result" onclick="window.location = \'<%= browse_episodes_path(show_slug: show.slug) %>\'"><div class="image"><%= image_tag show.image_url(:preview) %></div><div class="desc"><span class="name"><%= show.name %></span><br/><span class="episodes"><%= pluralize(show.episode_count, "Episode") %></span></div></div>')
    <% end %>
    $('#search_result_list').show()
<% else %>
    $('#search_placeholder').html('No Results Found')
    $('#search_result_list').html('')
<% end %>

app/views/videos/remote_sign_in_for_video.js.erb
<% if @error.nil? %>
    <% if params[:content_type] == 'Channel' %>
        window.location = '/watch/live/<%= params[:channel_slug] %>'
    <% elsif params[:content_type] == 'Show' %>
        <% if params[:episode_num].present? %>
            window.location = '/watch/shows/<%= params[:show_slug] %>/<%= params[:episode_num] %>'
        <% else %>
            window.location = '/watch/shows/<%= params[:show_slug] %>'
        <% end %>
    <% elsif params[:content_type] == 'Movie' %>
        window.location = '/watch/movies/<%= params[:movie_slug] %>'
    <% elsif params[:content_type] == 'Grid' %>
        window.location = '/watch/grid/<%= params[:grid_id] %>'
    <% end %>
<% else %>
    $('#password').after('<div class="text-danger" id="login-error"><%= @error %></div>')
<% end %>

app/views/videos/search_channels.js.erb
$('#channel_search_list').html('<%= escape_javascript(render("videos/partials/channel_search_list")) %>').show()

app/views/videos/search_shows.js.erb
$('#show_search_list').html('<%= escape_javascript(render("videos/partials/show_search_list")) %>').show()

app/views/videos/update_channel.js.erb
$('#name-error').remove()
$('#stream_url-error').remove()
$('#content_type-error').remove()
$('#free-error').remove()
$('#content_quality-error').remove()
$('#bitrate-error').remove()
$('#synopsis-error').remove()
$('#stream_name-error').remove()
$('#web_url-error').remove()
<% if @channel.errors.any? %>
    <% if @channel.errors[:name].present? %>
        $('#name').after('<div class="text-danger" id="name-error">Name <%= @channel.errors[:name].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:stream_url].present? %>
        $('#stream_url').after('<div class="text-danger" id="stream_url-error">Stream URL <%= @channel.errors[:stream_url].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:content_type].present? %>
        $('#content_type').after('<div class="text-danger" id="content_type-error">Content type <%= @channel.errors[:content_type].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:free].present? %>
        $('#free').after('<div class="text-danger" id="free-error">Membership <%= @channel.errors[:free].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:content_quality].present? %>
        $('#content_quality').after('<div class="text-danger" id="content_quality-error">Content quality <%= @channel.errors[:content_quality].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:bitrate].present? %>
        $('#bitrate').after('<div class="text-danger" id="bitrate-error">Bitrate <%= @channel.errors[:bitrate].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:synopsis].present? %>
        $('#synopsis').after('<div class="text-danger" id="synopsis-error">Synopsis <%= @channel.errors[:synopsis].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:stream_name].present? %>
        $('#stream_name').after('<div class="text-danger" id="stream_name-error">Stream name <%= @channel.errors[:stream_name].join(", ") %>.</div>')
    <% end %>
    <% if @channel.errors[:web_url].present? %>
        $('#web_url').after('<div class="text-danger" id="web_url-error">Web URL <%= @channel.errors[:web_url].join(", ") %>.</div>')
    <% end %>
    $('#details-title').html('Channel Details - <span class="text-danger">Not Updated</span>')
<% else %>
    var labels = jQuery.makeArray($('label.edited'))
    $.each(labels, function(index,element){
        $(element).html($(element).html().replace(' - <span class="edited-tag">Edited</span>',''))
        $(element).addClass('unedited')
    })
    $('#details-title').html('Channel Details - <span class="text-success">Updated</span>')
    $('#channel_<%= @channel.id %>').html('<%= escape_javascript(render("admins/cms_partials/channel_list_item")) %>')
    $('#edited_by').html("<%= @channel.edited_by_admin %><br/><small><%= @channel.updated_at.strftime('%B %-d, %Y at %H:%M') %></small>")
<% end %>

app/views/videos/update_episode.js.erb
$('#edit_ep_title-error').remove()
$('#edit_ep_episode_number-error').remove()
$('#edit_ep_stream_url-error').remove()
$('#edit_ep_release_date-error').remove()
$('#edit_ep_content_type-error').remove()
$('#edit_ep_content_quality-error').remove()
$('#edit_ep_bitrate-error').remove()
$('#edit_ep_length-error').remove()
$('#edit_ep_stream_name-error').remove()

<% if @episode.errors.any? %>
    <% if @episode.errors[:title].present? %>
        $('#edit_ep_title').after('<div class="text-danger" id="edit_ep_title-error">Title <%= @episode.errors[:title].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:episode_number].present? %>
        $('#edit_ep_episode_number').after('<div class="text-danger" id="edit_ep_episode_number-error">Episode number <%= @episode.errors[:episode_number].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:stream_url].present? %>
        $('#edit_ep_stream_url').after('<div class="text-danger" id="edit_ep_stream_url-error">Streaming URL <%= @episode.errors[:stream_url].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:release_date].present? %>
        $('#edit_ep_release_date').after('<div class="text-danger" id="edit_ep_release_date-error">Release date <%= @episode.errors[:release_date].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:content_type].present? %>
        $('#edit_ep_content_type').after('<div class="text-danger" id="edit_ep_content_type-error">Content type <%= @episode.errors[:content_type].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:content_quality].present? %>
        $('#edit_ep_content_quality').after('<div class="text-danger" id="edit_ep_content_quality-error">Content quality <%= @episode.errors[:content_quality].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:bitrate].present? %>
        $('#edit_ep_bitrate').after('<div class="text-danger" id="edit_ep_bitrate-error">Bitrate <%= @episode.errors[:bitrate].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:length].present? %>
        $('#edit_ep_length').after('<div class="text-danger" id="edit_ep_length-error">Length <%= @episode.errors[:length].join(", ") %>.</div>')
    <% end %>
    <% if @episode.errors[:stream_name].present? %>
        $('#edit_ep_stream_name').after('<div class="text-danger" id="edit_ep_stream_name-error">Stream name <%= @episode.errors[:stream_name].join(", ") %>.</div>')
    <% end %>
<% else %>
    $('#show_<%= @show.id %>').html('<%= escape_javascript(render("admins/cms_partials/show_list_item")).html_safe %>')
    $('#search_show_<%= @show.id %>').html('<%= escape_javascript(render("admins/cms_partials/show_list_item")).html_safe %>')
    $('#episode_wrapper').html('<%= escape_javascript(render("admins/cms_partials/episode_list")).html_safe %>')
    $('#edit_episode_modal').modal('hide')
    $('#edit_ep_title').val('')
    $('#edit_ep_stream_url').val('')
    $('#edit_ep_release_date').val('')
    $('#edit_ep_episode_number').val('')
    $('#edit_ep_synopsis').val('')
<% end %>

app/views/videos/update_grid.js.erb
<% unless @category.errors.any? %>
    window.location = '/admins/videos/home_grid'
<% else %>
    $('#name-error').remove()
    $('#rank-error').remove()
    $('#item_type-error').remove()
    $('#free-error').remove()
    <% if @category.errors[:name].present? %>
        $('#name').after('<div class="text-danger" id="name-error">Name <%= @category.errors[:name].join(", ") %>.</div>')
    <% end %>
    <% if @category.errors[:rank].present? %>
        $('#rank').after('<div class="text-danger" id="rank-error">Grid number <%= @category.errors[:rank].join(", ") %>.</div>')
    <% end %>
    <% if @category.errors[:item_type].present? %>
        $('#item_type').after('<div class="text-danger" id="item_type-error">Class filter <%= @category.errors[:item_type].join(", ") %>.</div>')
    <% end %>
    <% if @category.errors[:free].present? %>
        $('#free').after('<div class="text-danger" id="free-error">Membership <%= @category.errors[:free].join(", ") %>.</div>')
    <% end %>
<% end %>

app/views/videos/update_movie.js.erb
$('#name-error').remove()
$('#stream_url-error').remove()
$('#content_type-error').remove()
$('#free-error').remove()
$('#content_quality-error').remove()
$('#bitrate-error').remove()
$('#synopsis-error').remove()
$('#length-error').remove()
$('#release_date-error').remove()
$('#front_page-error').remove()
$('#web_url-error').remove()
<% if @movie.errors.any? %>
    <% if @movie.errors[:name].present? %>
        $('#name').after('<div class="text-danger" id="name-error">Name <%= @movie.errors[:name].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:stream_url].present? %>
        $('#stream_url').after('<div class="text-danger" id="stream_url-error">Stream URL <%= @movie.errors[:stream_url].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:content_type].present? %>
        $('#content_type').after('<div class="text-danger" id="content_type-error">Content type <%= @movie.errors[:content_type].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:free].present? %>
        $('#free').after('<div class="text-danger" id="free-error">Membership <%= @movie.errors[:free].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:content_quality].present? %>
        $('#content_quality').after('<div class="text-danger" id="content_quality-error">Content quality <%= @movie.errors[:content_quality].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:bitrate].present? %>
        $('#bitrate').after('<div class="text-danger" id="bitrate-error">Bitrate <%= @movie.errors[:bitrate].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:synopsis].present? %>
        $('#synopsis').after('<div class="text-danger" id="synopsis-error">Synopsis <%= @movie.errors[:synopsis].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:length].present? %>
        $('#length').after('<div class="text-danger" id="length-error">Length <%= @movie.errors[:length].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:release_date].present? %>
        $('#release_date').after('<div class="text-danger" id="release_date-error">Release date <%= @movie.errors[:release_date].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:hd].present? %>
        $('#front_page').after('<div class="text-danger" id="front_page-error"><%= @movie.errors[:hd].join(", ") %>.</div>')
    <% end %>
    <% if @movie.errors[:web_url].present? %>
        $('#web_url').after('<div class="text-danger" id="web_url-error">Web URL <%= @movie.errors[:web_url].join(", ") %>.</div>')
    <% end %>
    $('#details-title').html('Channel Details - <span class="text-danger">Not Updated</span>')
<% else %>
    var labels = jQuery.makeArray($('label.edited'))
    $.each(labels, function(index,element){
        $(element).html($(element).html().replace(' - <span class="edited-tag">Edited</span>',''))
        $(element).addClass('unedited')
    })
    $('#details-title').html('Channel Details - <span class="text-success">Updated</span>')
    $('#movie_<%= @movie.id %>').html('<%= escape_javascript(render("admins/cms_partials/movie_list_item")) %>')
    $('#edited_by').html("<%= @movie.edited_by_admin %><br/><small><%= @movie.updated_at.strftime('%B %-d, %Y at %H:%M') %></small>")
<% end %>

app/views/videos/update_movie_image.js.erb
<% if @success == true %>
    $('#hd_image_preview').html('<%= image_tag @movie.image_url(:hd) %>')
    $('#sd_image_preview').html('<%= image_tag @movie.image_url(:sd) %>')
    $('#movie_<%= @movie.id %>').children('.image_wrapper').html('<%= image_tag @movie.image_url(:preview) %>')
    $('#movie_search_<%= @movie.id %>').children('.image_wrapper').html('<%= image_tag @movie.image_url(:preview) %>')
    $('#edited_by').html("<%= @movie.edited_by_admin %><br/><small><%= @movie.updated_at.strftime('%B %-d, %Y at %H:%M') %></small>")
<% end %>

app/views/videos/view_grid.js.erb
$('#name').val('<%= @category.name %>')
$('#rank').val('<%= @category.rank %>')
$('#genre').val('<%= @category.genre %>')
$('#item_type').val('<%= @category.item_type %>')
$('#content_type').val('<%= @category.content_type %>')
$('#content_quality').val('<%= @category.content_quality %>')
$('#free').val('<%= @category.free %>')
$('#front_page').val('<%= @category.front_page %>')
$('#sort').val('<%= @category.sort %>')
$('#id').val(<%= @category.id %>)
$('#edit_grid_modal').modal('show')