config/routes.rb
        get '/admins/migrations/vod/new' => 'vod_migrations#new_vod_upload', as: 'new_vod_upload'
        post 'start_vod_upload' => 'vod_migrations#start_upload'
        get '/admins/migrations/vod' => 'admins#vod_uploads', as: 'vod_uploads'
        get '/admins/migrations/vod/:id' => 'admins#view_vod_upload', as: 'view_vod_upload'

        get '/admins/migrations/client/new' => 'admins#new_client_upload', as: 'new_client_upload'
        post 'start_client_upload' => 'client_migrations#start_upload'
        get '/admins/migrations/client' => 'admins#client_uploads', as: 'client_uploads'
        get '/admins/migrations/client/:id' => 'admins#view_client_upload', as: 'view_client_upload'


        get 'admin_show_existing_grids' => 'admins#show_existing_grids'
        get 'show_sub_expiry' => 'admins#show_sub_expiry'

        mount ResqueWeb::Engine => "/resque_web"
        get '/admins/notifications/view/:id' => 'admin_notifications#notification_redirect', as: 'admin_view_notification'
        get 'clear_notifs' => 'admin_notifications#clear'

  	  	get '/admins' => 'admins#index', as: 'admins'

        get 'admin_view_client_reg_report' => 'admins#view_client_reg_report'
        get 'admin_view_orders_report' => 'admins#view_orders_report'
        get 'admin_view_support_report' => 'admins#view_support_report'

        # General Settings
        get '/admins/settings' => 'admins#general_settings', as: 'general_settings'

        get '/admins/settings/timezone' => 'admins#edit_timezone', as: 'edit_timezone'
        post 'update_default_timezone' => 'admins#update_default_timezone'

        get '/admins/settings/languages' => 'admins#edit_languages', as: 'edit_languages'
        post 'update_languages' => 'admins#update_languages'

        get '/admins/settings/registration_sign_in' => 'admins#edit_registration', as: 'edit_registration'
        post 'update_registration' => 'admins#update_registration'

        get '/admins/settings/payouts' => 'admins#edit_payouts', as: 'edit_payouts'
        post 'update_payout_methods' => 'admins#update_payout_methods'

        get '/admins/settings/device_limit' => 'admins#edit_device_limit', as: 'edit_device_limit'
        post 'update_device_limit' => 'admins#update_device_limit'

        get '/admins/settings/free_trial' => 'admins#edit_free_trial', as: 'edit_free_trial'
        post 'update_free_trial' => 'admins#update_free_trial'

        get '/admins/settings/contact_email' => 'admins#edit_contact_email', as: 'edit_contact_email'
        post 'update_contact_email' => 'admins#update_contact_email'

        get '/admins/settings/wd_limits' => 'admins#edit_wd_limits', as: 'edit_wd_limits'
        post 'update_lower_wd_limit' => 'admins#update_lower_wd_limit'
        post 'update_upper_wd_limit' => 'admins#update_upper_wd_limit'

        get '/admins/settings/footer' => 'admins#edit_footer_content', as: 'edit_footer_content'
        post 'update_footer_content' => 'admins#update_footer_content'


  		# Manage Users
  		get '/admins/users' => 'admins#users', as: 'search_users'
        get '/admins/users/all' => 'admins#all_users', as: 'all_users'
        get 'admin_search_users_table' => 'admins#search_users_table'
  		get 'side_search_users' => 'admins#search_users'
        get '/admins/users/profile/:id' => 'admins#view_user', as: 'view_user'
        get '/admins/users/transactions/:id' => 'admins#view_user_transactions', as: 'view_user_transactions'
        get '/admins/users/devices/:id' => 'admins#view_user_devices', as: 'view_user_devices'
        get '/admins/users/notes/:id' => 'admins#view_user_notes', as: 'view_user_notes'
        get '/admins/users/subscription_adjustment/:id' => 'admins#view_user_subscription', as: 'view_user_subscription'
        get '/admins/users/balance_adjustment/:id' => 'admins#view_user_balance', as: 'view_user_balance'

        get 'reset_user_password' => 'admins#reset_user_password'
        post 'manual_reset_user_password' => 'admins#manual_reset_user_password'

        post 'update_user_roku_account' => 'admins#update_user_roku_account'
        post 'update_user_language' => 'admins#update_user_language'

        post 'admin_update_user_profile' => 'admins#update_user_profile'
        post 'admin_update_user_mailing' => 'admins#update_user_mailing'
        post 'extend_user_subscription' => 'admins#extend_user_subscription'
        get 'cancel_user_subscription' => 'admins#cancel_user_subscription'
        post 'update_user_balance' => 'admins#update_user_balance'
        post 'admin_create_transaction' => 'admins#create_transaction'
        post 'admin_register_device' => 'admins#register_device'
        get 'admin_unlink_device' => 'admins#unlink_device'
        get 'admin_toggle_user_status' => 'admins#toggle_user_status'

        post 'add_note_to_user' => 'users#add_note'
        post 'add_image_to_note' => 'users#add_image_to_note'
        post 'update_note' => 'users#update_note'
        post 'add_image_to_existing_note' => 'users#add_image_to_existing_note'
        get 'delete_note_file' => 'users#delete_note_file'
        get 'delete_note' => 'users#delete_note'
        get 'delete_unsaved_note' => 'users#delete_unsaved_note'

        get 'admin_choose_plan' => 'admins#choose_plan'
        post 'admin_add_subscription' => 'admins#add_subscription'
        post 'admin_add_subscription_user' => 'admins#add_subscription_user'

  		get '/admins/new_user' => 'admins#new_user', as: 'new_user'
  		post 'admin_create_user' => 'admins#create_user'

        get '/admins/users/pending_payments' => 'admins#user_payment_queue'

        # Transactions
        get '/admins/orders' => 'admins#orders', as: 'orders'
        get '/admins/orders/new' => 'admins#new_transaction', as: 'new_tx'
        post 'admin_create_transaction' => 'admins#create_transaction'
        get '/admins/orders/pending' => 'admins#pending_transactions', as: 'pending_tx'
        get '/admins/orders/paid' => 'admins#paid_transactions', as: 'paid_tx'
        get '/admins/orders/refunded' => 'admins#refunded_transactions', as: 'refunded_tx'
        get '/admins/orders/cancelled' => 'admins#cancelled_transactions', as: 'cancelled_tx'
        get '/admins/orders/view/:id' => 'transactions#show', as: 'view_tx'
        post 'update_transaction_dates' => 'transactions#update_dates'

        post 'create_tx_standalone' => 'transactions#create_standalone'

        post 'create_tx_user' => 'transactions#create_user'

        get 'accept_payment' => 'transactions#accept'
        get 'cancel_payment' => 'transactions#cancel'
        get 'refund_payment' => 'transactions#refund'

  		# Video CMS
        get '/admins/videos/tv_shows' => 'admins#shows', as: 'tv_shows'
        get 'view_show' => 'videos#view_show'

        get '/admins/videos/movies' => 'admins#movies', as: 'movies'
        get 'view_movie' => 'videos#view_movie'

  		get '/admins/videos/live_channels' => 'admins#live_channels', as: 'live_channels'
  		get 'view_channel' => 'videos#view_channel'
        get 'delete_channel' => 'videos#delete_channel'

        post 'add_show' => 'videos#add_show'
        post 'update_show' => 'videos#update_show'
        post 'update_show_image' => 'videos#update_show_image'
        post 'update_show_banner' => 'videos#update_show_banner'
        get 'delete_show' => 'videos#delete_show'

        get 'search_shows' => 'videos#search_shows'
        get 'search_episodes' => 'videos#search_episodes'
        get 'delete_episode' => 'videos#delete_episode'

        post 'add_episode' => 'videos#add_episode'
        post 'update_episode' => 'videos#update_episode'
        get 'view_episode' => 'videos#view_episode'

        post 'add_channel' => 'videos#add_channel'
        post 'update_channel' => 'videos#update_channel'
        post 'update_channel_image' => 'videos#update_channel_image'
        post 'update_channel_banner' => 'videos#update_channel_banner'

        get 'search_channels' => 'videos#search_channels'

        post 'add_movie' => 'videos#add_movie'
        post 'update_movie' => 'videos#update_movie'
        post 'update_movie_image' => 'videos#update_movie_image'
        post 'update_movie_banner' => 'videos#update_movie_banner'
        get 'delete_movie' => 'videos#delete_movie'

        get 'search_movies' => 'videos#search_movies'
        get 'admin_show_all_grids' => 'admins#show_all_grids'
        get 'admin_show_existing_grids' => 'admins#show_existing_grids'

        get '/admins/videos/broken' => 'admins#broken_links', as: 'admin_broken_links'
        get 'mark_broken_as_resolved' => 'admins#mark_broken_as_resolved'

        get '/admins/videos/grids/all' => 'admins#all_grids', as: 'admin_all_grids'
        get '/admins/videos/grids/home' => 'admins#home_grid', as: 'admin_home_grid'
        get '/admins/videos/grids/view/:id' => 'admins#view_grid', as: 'admin_view_grid'
        post 'admin_update_grid' => 'admins#update_grid'
        post 'admin_update_grid_image' => 'admins#update_grid_image'
        get '/admins/videos/grids/new' => 'admins#new_grid', as: 'admin_new_grid'
        post 'admin_create_grid' => 'admins#create_grid'
        get 'delete_grid' => 'admins#delete_grid'

        post 'add_grid' => 'videos#add_grid'
        post 'update_grid_items' => 'videos#update_grid_items'

        get 'refresh_grid_view' => 'videos#refresh_grid'

      	# Manage Sales Reps
      	get '/admins/sales_reps' => 'admins#sales_reps', as: 'search_reps_main'
      	get 'search_reps' => 'admins#search_reps'
      	get '/admins/sales_reps/view/:id' => 'admins#view_rep', as: 'view_rep'
      	get '/admins/new_sales_rep' => 'admins#new_sales_rep', as: 'new_rep'
      	post 'admin_create_sales_rep' => 'admins#create_sales_rep'

        get 'reset_rep_password' => 'admins#reset_rep_password'
        post 'manual_reset_rep_password' => 'admins#manual_reset_rep_password'

        post 'admin_update_rep_profile' => 'admins#update_rep_profile'

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/accept.js.erb
window.location = '<%= view_tx_path(id: @transaction.id) %>'

app/views/transactions/cancel.js.erb
window.location = '<%= view_tx_path(id: @transaction.id) %>'

app/views/transactions/index.html.erb
<% content_for :top_level, 'Orders/Transactions' %>
<% content_for :low_levels, YAML.dump([]) %>
<div id="left-scroll" class="nano">
    <div class="nano-content">

        <div class="panel">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-6">
                        Order List
                    </div>
                </div>
            </div>
            <div class="panel-body plr20">
            	<div class="row">
                    <%= form_tag all_tx_search_path, method: :get do %>
                	<div class="col-sm-6">
                        <div class="form-group has-feedback feedback-wt">
                            <%= text_field_tag :search, params[:search], class: 'form-control input-md', placeholder: "Search by Order# or Client" %>
                            <span class="glyphicon glyphicon-search form-control-feedback"></span>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <%= select_tag :payment_type, options_for_select([['Payment Method',nil],'Credit Card','Money Order','Bank Transfer','Cheque'], params[:payment_type]), class: 'form-control input-md' %>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <%= select_tag :status, options_for_select([['Status',nil],'Pending','Paid','Cancelled','Refunded'], params[:status]), class: 'form-control input-md' %>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <%= submit_tag 'Filter Orders', class: 'btn btn-default btn-md btn-block' %>
                    </div>
                    <% end %>
                </div>
                <div class="table-responsive">
                <table class="table table-list fz11-5 table-hover" id='tx_table'>
                	<thead>
                    <tr>
                        <td>Order Number
                        	<span class="sort">
                            	<span class="fa fa-angle-up"></span>
                                <span class="fa fa-angle-down"></span>
                            </span>
                        </td>
                        <td>Client
                        	<span class="sort">
                            	<span class="fa fa-angle-up"></span>
                                <span class="fa fa-angle-down"></span>
                            </span>
                        </td>
                        <td>Payment Method
                        	<span class="sort">
                            	<span class="fa fa-angle-up"></span>
                                <span class="fa fa-angle-down"></span>
                            </span>
                        </td>
                        <td>Date Created
                        	<span class="sort">
                            	<span class="fa fa-angle-up"></span>
                                <span class="fa fa-angle-down"></span>
                            </span>
                        </td>
                        <td>Date Paid
                            <span class="sort">
                                <span class="fa fa-angle-up"></span>
                                <span class="fa fa-angle-down"></span>
                            </span>
                        </td>
                        <td>Status
                            <span class="sort">
                                <span class="fa fa-angle-up"></span>
                                <span class="fa fa-angle-down"></span>
                            </span>
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                        <% @transactions.each do |tx| %>
                    <tr onclick='window.location = "<%= view_tx_path(id: tx.id) %>"' style='cursor:pointer'>
                    	<td class="text-bold">#<%= tx.id %></td>
                        <% user = User.where(id: tx.user_id).first %>
                    	<% if user.nil? %>
                            <td>User not found</td>
                        <% else %>
                            <td><%= user.name %></td>
                        <% end %>
                        <td><%= tx.payment_type %></td>
                    	<td><%= tx.created_at.strftime('%Y/%m/%-d') %></td>
                    	<td>
                            <% if tx.customer_paid.present? %>
                                <%= tx.customer_paid.strftime('%Y/%m/%-d') %>
                            <% else %>
                                N/A
                            <% end %>
                        </td>
                        <td class='<%= tx.status.downcase %>'><%= tx.status %></td>
                    </tr>
                    <% end %>
                    </tbody>
                </table>
                </div>
            </div>
        </div>

	</div>
</div>
<script>
$('#tx_table').dataTable();
$('#tx_table_filter').html('<label>Filter Results:<input type="search" class="form-control input-sm" aria-controls="tx_table"></label>')
$('#all_tx').addClass('active')
</script>

app/views/transactions/refund.js.erb
<% if @success == true %>
    window.location = '<%= view_tx_path(id: @transaction.id) %>'
<% else %>
    addNotification('error', '<%= @message %>', 'Error', 'check-circle')
<% end %>

app/views/transactions/show.html.erb
<% content_for :top_level, 'Orders/Transactions' %>
<% content_for :low_levels, YAML.dump(["Order #{@transaction.id}"]) %>
<div id="left-scroll" class="nano">
    <div class="nano-content">
        <div class='row'>
            <div class='col-xs-12'>
                <div class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <% name = @data[:name].gsub('REFUNDED: ','').gsub('PAID: ','').gsub('CANCELLED: ','') %>
                                    <div class="number"><%= name %></div>
                                    Plan
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <div class="number" id='user_balance'>$<%= number_with_precision(@data[:price], precision: 2) %></div>
                                    Order Amount
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <% if @transaction.balance_used.nil? %>
                                        <div class="number">$<%= number_with_precision(@data[:price], precision: 2) %></div>
                                    <% else %>
                                        <div class="number">$<%= number_with_precision(@data[:price] - @transaction.balance_used, precision: 2) %></div>
                                    <% end %>
                                    Amount Owing
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-number">
                                    <div class="number <%= @transaction.status.downcase %>"><%= @transaction.status %></div>
                                    Status
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='row'>
            <div class='col-md-6'>
                <div class="panel">
                    <div class='panel-heading'>
                        <h3 class='panel-title'>Transaction Details</h3>
                    </div>
                    <div class='panel-body'>
                        <% if @user.nil? %>
                            <div class="stat-number">
                                <div class="number">User Not Found</div>
                            </div>
                        <% else %>
                            <div class='row'>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Client Name:</strong><br/><%= @user.name %></p>
                                </div>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Client Email:</strong><br/><%= @user.email %></p>
                                </div>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Client Membership:</strong><br/><% if @user.premium? %>Premium<% else %>Free<% end %></p>
                                </div>
                            </div>
                        <% end %>
                        <div class='row'>
                            <div class='col-lg-4 col-sm-6'>
                                <p><strong style='font-size: 105%'>Order Date:</strong><br/><%= @transaction.created_at.strftime('%Y/%m/%d') %></p>
                            </div>
                            <div class='col-lg-4 col-sm-6'>
                                <p><strong style='font-size: 105%'>Paid Date:</strong><br/>
                                    <% if @transaction.customer_paid.present? %>
                                        <%= @transaction.customer_paid.strftime('%Y/%m/%d') %>
                                    <% else %>
                                        N/A
                                    <% end %>
                                </p>
                            </div>
                            <div class='col-lg-4 col-sm-6'>
                                <p><strong style='font-size: 105%'>Refund Date:</strong><br/>
                                    <% if @transaction.customer_refunded.present? %>
                                        <%= @transaction.customer_refunded.strftime('%Y/%m/%d') %>
                                    <% else %>
                                        N/A
                                    <% end %>
                                </p>
                            </div>
                        </div>
                        <div class='row'>
                            <% if @roku_attached == true %>
                            <div class='col-lg-4 col-sm-6'>
                                <p><strong style='font-size: 105%'>Subscription Type:</strong><br/>Roku</p>
                            </div>
                            <div class='col-lg-4 col-sm-6'>
                                <% unless @roku.nil? %>
                                <p><strong style='font-size: 105%'>Roku Serial:</strong><br/><%= @roku.serial %></p>
                                <% else %>
                                <p><strong style='font-size: 105%'>Roku Serial:</strong><br/>Not Found</p>
                                <% end %>
                            </div>
                            <% else %>
                            <div class='col-lg-4 col-sm-6'>
                                <p><strong style='font-size: 105%'>Subscription Type:</strong><br/>Web/Mobile/Tablet</p>
                            </div>
                            <% end %>
                            <div class='col-lg-4 col-sm-6'>
                                <p><strong style='font-size: 105%'>Payment Method:</strong><br/><%= @transaction.payment_type %></p>
                            </div>
                        </div>

                    </div>
                    <div class='panel-footer'>
                        <%= link_to 'View PDF Invoice', view_invoice_path(id: @transaction.id), class: 'btn btn-primary', style: 'width: 100%', target: '_blank' %>
                    </div>
                </div>
            </div>
            <div class='col-md-6'>
                <% if @transaction.status == 'Pending' || @transaction.status == 'Paid' %>
                    <div class="panel">
                        <div class='panel-heading'>
                            <h3 class='panel-title'>Actions</h3>
                        </div>
                        <div class='panel-body'>
                            <% if @transaction.status == 'Pending' %>
                                <div class='col-sm-6'>
                                    <%= link_to 'Accept Payment', accept_payment_path(id: @transaction.id), class: 'btn btn-success', style: 'width: 100%', data: {disable_with: 'Processing...'}, remote: true %>
                                </div>
                                <div class='col-sm-6'>
                                    <%= link_to 'Cancel Payment', cancel_payment_path(id: @transaction.id), class: 'btn btn-danger', style: 'width: 100%', data: {disable_with: 'Processing...'}, remote: true %>
                                </div>
                            <% elsif @transaction.status == 'Paid' %>
                                <div class='col-sm-6 col-centered'>
                                    <%= link_to 'Refund Payment', refund_payment_path(id: @transaction.id), class: 'btn btn-info', style: 'width: 100%', data: {disable_with: 'Processing...'}, remote: true %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %>
                <div class="panel">
                    <div class='panel-heading'>
                        <h3 class='panel-title'>Sales Representative Details</h3>
                    </div>
                    <div class='panel-body'>
                        <% if @rep.nil? %>
                            <div class="stat-number">
                                <div class="number">No Representative Attached</div>
                            </div>
                        <% else %>
                            <div class='row'>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Rep Name:</strong><br/><%= @rep.name %></p>
                                </div>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Rep Email:</strong><br/><%= @rep.email %></p>
                                </div>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Rep Company:</strong><br/><%= @rep.company %></p>
                                </div>
                            </div>
                            <div class='row'>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Commission Rate:</strong><br/><%= @data[:commission_rate] %>%</p>
                                </div>
                                <div class='col-lg-4 col-sm-6'>
                                    <p><strong style='font-size: 105%'>Commission Amount:</strong><br/>
                                        $<%= number_with_precision(@data[:commission_rate].to_f/100 * @data[:price], precision: 2) %>
                                    </p>
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/transactions/update_dates.js.erb
<% if @dates_valid == true %>
    <% flash[:success] = 'Subscription Updated' %>
    window.location = '<%= view_tx_path(id: @transaction.id) %>'
<% else %>
    addNotification('error', 'Please choose a valid date range', 'Error', 'exclamation-circle')
<% end %>