config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :sales_representatives
  devise_for :users

        get 'video_search' => 'videos#navbar_search'


        get '/watch/grid/:category_id' => 'videos#full_grid', as: 'full_grid'

        get '/grid/:id' => 'videos#grid'

        get '/watch/live/:channel_slug' => 'videos#watch_channel', as: 'watch_channel'

        get '/watch/movies/:movie_slug' => 'videos#watch_movie', as: 'watch_movie'

        get '/watch/shows/:show_slug' => 'videos#browse_episodes', as: 'browse_episodes'
        # All or page


        get '/watch/shows/:show_slug/:episode_number' => 'videos#watch_episode', as: 'watch_episode'

        post 'remote_sign_in_for_video' => 'videos#remote_sign_in_for_video'
        post 'remote_sign_in' => 'users#remote_sign_in'

        get 'subscribe_newsletter_footer' => 'users#subscribe_newsletter_footer'

        get 'grid_view' => 'videos#grid_view'
        get '/site/500' => 'site#part', as: 'inactive'
  	# User Methods
    authenticate :user do
        get 'update_show_time' => 'time#update_show'
        get 'mark_episode_complete' => 'time#mark_episode_complete'
        get 'mark_show_complete' => 'time#mark_show_complete'

        get 'submit_broken_link' => 'videos#submit_broken_link'


        get 'update_movie_time' => 'time#update_movie'
        get 'mark_movie_complete' => 'time#mark_movie_complete'


  	  	get 'account' => 'users#account'

        get '/account/devices' => 'users#devices', as: 'my_devices'
        get '/account/billing' => 'users#billing', as: 'my_billing'
        get '/account/support' => 'users#support', as: 'my_support'

        get '/account/new_ticket' => 'users#new_ticket', as: 'user_new_ticket'
        post 'user_create_ticket' => 'support#user_create_ticket'
        get 'user_view_ticket' => 'support#user_view_ticket'
        post 'user_send_message_on_ticket' => 'support#user_send_message'
        post 'user_attach_file_to_ticket' => 'support#user_attach_file'

        get 'view_device/:id' => 'users#view_device', as: 'view_device'
        post 'update_roku' => 'users#update_roku'
        post 'update_device' => 'users#update_device'
        post 'register_new_device' => 'users#register_new_device'
        get 'unlink_device' => 'users#unlink_device'

        post 'update_profile' => 'users#update_profile'

        get 'subscribe' => 'users#subscribe'
        get 'view_plan' => 'users#view_plan'
        post 'add_subscription' => "users#add_subscription"

        get '/account/settings' => 'users#settings', as: 'user_settings'
        post 'user_reset_password' => 'users#reset_password'
        get 'user_subscribe_to_mailchimp' => 'users#subscribe_to_mailchimp'
        get 'user_unsubscribe_from_mailchimp' => 'users#unsubscribe_from_mailchimp'

        get 'start_free_trial' => 'users#start_free_trial'

    end

  	# Admin Methods
    authenticate :admin do
        get '/admins/expiry_report' => 'admins#expiry_report', as: 'expiry_report'
        get '/admins/pdf_expiry_report' => 'admins#pdf_expiry_report', as: 'pdf_expiry_report'


        get 'admin_load_devices' => 'admins#load_devices'

        get 'delete_user' => 'admins#delete_user'
        get 'delete_rep' => 'admins#delete_rep'

        post 'create_client_upload' => 'admins#upload_customers'

        get '/admins/migrations/vod/new' => 'vod_migrations#new_vod_upload', as: 'new_vod_upload'
        post 'start_vod_upload' => 'vod_migrations#start_upload'
        get '/admins/migrations/vod' => 'admins#vod_uploads', as: 'vod_uploads'
        get '/admins/migrations/vod/:id' => 'admins#view_vod_upload', as: 'view_vod_upload'

        get '/admins/migrations/client/new' => 'admins#new_client_upload', as: 'new_client_upload'
        post 'start_client_upload' => 'client_migrations#start_upload'
        get '/admins/migrations/client' => 'admins#client_uploads', as: 'client_uploads'
        get '/admins/migrations/client/:id' => 'admins#view_client_upload', as: 'view_client_upload'


        get 'admin_show_existing_grids' => 'admins#show_existing_grids'
        get 'show_sub_expiry' => 'admins#show_sub_expiry'

        mount ResqueWeb::Engine => "/resque_web"
        get '/admins/notifications/view/:id' => 'admin_notifications#notification_redirect', as: 'admin_view_notification'
        get 'clear_notifs' => 'admin_notifications#clear'

  	  	get '/admins' => 'admins#index', as: 'admins'

        get 'admin_view_client_reg_report' => 'admins#view_client_reg_report'
        get 'admin_view_orders_report' => 'admins#view_orders_report'
        get 'admin_view_support_report' => 'admins#view_support_report'

        # General Settings
        get '/admins/settings' => 'admins#general_settings', as: 'general_settings'

        get '/admins/settings/timezone' => 'admins#edit_timezone', as: 'edit_timezone'
        post 'update_default_timezone' => 'admins#update_default_timezone'

        get '/admins/settings/languages' => 'admins#edit_languages', as: 'edit_languages'
        post 'update_languages' => 'admins#update_languages'

        get '/admins/settings/registration_sign_in' => 'admins#edit_registration', as: 'edit_registration'
        post 'update_registration' => 'admins#update_registration'

        get '/admins/settings/payouts' => 'admins#edit_payouts', as: 'edit_payouts'
        post 'update_payout_methods' => 'admins#update_payout_methods'

        get '/admins/settings/device_limit' => 'admins#edit_device_limit', as: 'edit_device_limit'
        post 'update_device_limit' => 'admins#update_device_limit'

        get '/admins/settings/free_trial' => 'admins#edit_free_trial', as: 'edit_free_trial'
        post 'update_free_trial' => 'admins#update_free_trial'

        get '/admins/settings/contact_email' => 'admins#edit_contact_email', as: 'edit_contact_email'
        post 'update_contact_email' => 'admins#update_contact_email'

        get '/admins/settings/wd_limits' => 'admins#edit_wd_limits', as: 'edit_wd_limits'
        post 'update_lower_wd_limit' => 'admins#update_lower_wd_limit'
        post 'update_upper_wd_limit' => 'admins#update_upper_wd_limit'

        get '/admins/settings/footer' => 'admins#edit_footer_content', as: 'edit_footer_content'
        post 'update_footer_content' => 'admins#update_footer_content'


  		# Manage Users
  		get '/admins/users' => 'admins#users', as: 'search_users'
        get '/admins/users/all' => 'admins#all_users', as: 'all_users'
        get 'admin_search_users_table' => 'admins#search_users_table'
  		get 'side_search_users' => 'admins#search_users'
        get '/admins/users/profile/:id' => 'admins#view_user', as: 'view_user'
        get '/admins/users/transactions/:id' => 'admins#view_user_transactions', as: 'view_user_transactions'
        get '/admins/users/devices/:id' => 'admins#view_user_devices', as: 'view_user_devices'
        get '/admins/users/notes/:id' => 'admins#view_user_notes', as: 'view_user_notes'
        get '/admins/users/subscription_adjustment/:id' => 'admins#view_user_subscription', as: 'view_user_subscription'
        get '/admins/users/balance_adjustment/:id' => 'admins#view_user_balance', as: 'view_user_balance'

        get 'reset_user_password' => 'admins#reset_user_password'
        post 'manual_reset_user_password' => 'admins#manual_reset_user_password'

        post 'update_user_roku_account' => 'admins#update_user_roku_account'
        post 'update_user_language' => 'admins#update_user_language'

        post 'admin_update_user_profile' => 'admins#update_user_profile'
        post 'admin_update_user_mailing' => 'admins#update_user_mailing'
        post 'extend_user_subscription' => 'admins#extend_user_subscription'
        get 'cancel_user_subscription' => 'admins#cancel_user_subscription'
        post 'update_user_balance' => 'admins#update_user_balance'
        post 'admin_create_transaction' => 'admins#create_transaction'
        post 'admin_register_device' => 'admins#register_device'
        get 'admin_unlink_device' => 'admins#unlink_device'
        get 'admin_toggle_user_status' => 'admins#toggle_user_status'

        post 'add_note_to_user' => 'users#add_note'
        post 'add_image_to_note' => 'users#add_image_to_note'
        post 'update_note' => 'users#update_note'
        post 'add_image_to_existing_note' => 'users#add_image_to_existing_note'
        get 'delete_note_file' => 'users#delete_note_file'
        get 'delete_note' => 'users#delete_note'
        get 'delete_unsaved_note' => 'users#delete_unsaved_note'

        get 'admin_choose_plan' => 'admins#choose_plan'
        post 'admin_add_subscription' => 'admins#add_subscription'
        post 'admin_add_subscription_user' => 'admins#add_subscription_user'

  		get '/admins/new_user' => 'admins#new_user', as: 'new_user'
  		post 'admin_create_user' => 'admins#create_user'

        get '/admins/users/pending_payments' => 'admins#user_payment_queue'

        # Transactions
        get '/admins/orders' => 'admins#orders', as: 'orders'
        get '/admins/orders/new' => 'admins#new_transaction', as: 'new_tx'
        post 'admin_create_transaction' => 'admins#create_transaction'
        get '/admins/orders/pending' => 'admins#pending_transactions', as: 'pending_tx'
        get '/admins/orders/paid' => 'admins#paid_transactions', as: 'paid_tx'
        get '/admins/orders/refunded' => 'admins#refunded_transactions', as: 'refunded_tx'
        get '/admins/orders/cancelled' => 'admins#cancelled_transactions', as: 'cancelled_tx'
        get '/admins/orders/view/:id' => 'transactions#show', as: 'view_tx'
        post 'update_transaction_dates' => 'transactions#update_dates'

        post 'create_tx_standalone' => 'transactions#create_standalone'

        post 'create_tx_user' => 'transactions#create_user'

        get 'accept_payment' => 'transactions#accept'
        get 'cancel_payment' => 'transactions#cancel'
        get 'refund_payment' => 'transactions#refund'

  		# Video CMS

app/views/admins/nav/sidenavs/_admins.html.erb
<li id='new_admin'><%= link_to 'New Administrator', new_admin_path %></li>
<li id='all_admins'><%= link_to 'All Administrators', manage_admins_path %></li>

app/views/admins/nav/sidenavs/_general_settings.html.erb
<li id='timezone_side'><%= link_to 'Time Zone', edit_timezone_path %></li>
<li id='device_limit'><%= link_to 'Device Limit', edit_device_limit_path %></li>
<li id='free_trial'><%= link_to 'Free Trial', edit_free_trial_path %></li>
<li id='withdrawal_limits'><%= link_to 'Withdrawal Limits', edit_wd_limits_path %></li>
<li id='payouts'><%= link_to 'Payout Methods', edit_payouts_path %></li>
<li id='contact'><%= link_to 'Contact Email', edit_contact_email_path %></li>
<li id='footer'><%= link_to 'Footer Content', edit_footer_content_path %></li>
<li id='languages'><%= link_to 'User Languages', edit_languages_path %></li>
<li id='reg_side'><%= link_to 'Registration Status', edit_registration_path %></li>

app/views/admins/nav/sidenavs/_index.html.erb
<li><%= link_to 'New Client', new_user_path %></li>
<li><%= link_to 'New Sales Rep', new_rep_path %></li>
<li><%= link_to 'Support', admin_support_path %></li>
<li><%= link_to 'Orders', orders_path %></li>
<li id='expiry_report'><%= link_to 'Expirations', '#', style: 'cursor:pointer', onclick: 'window.location= "'+expiry_report_path(range: 0)+'"' %></li>
<li><%= link_to 'VOD Migrations', vod_uploads_path %></li>
<li><%= link_to 'Client Migrations', client_uploads_path %></li>

app/views/admins/nav/sidenavs/_mail.html.erb
<li id='mail_api'><%= link_to 'Server Settings', mail_settings_path %></li>
<li id='mail_markup'><%= link_to 'Default Markup', mail_markup_path %></li>
<% @templates.each do |template| %>
    <li id='mail_<%= template.name.gsub(" ","_").downcase %>'><%= link_to template.name, mail_template_path(id: template.id) %></a></li>
<% end %>

app/views/admins/nav/sidenavs/_migrations.html.erb
<li id='new_vod'><%= link_to 'New VOD Migration', new_vod_upload_path %></li>
<li id='all_vod'><%= link_to 'All VOD Migrations', vod_uploads_path %></li>
<li id='new_client'><%= link_to 'New Client Migration', new_client_upload_path %></li>
<li id='all_client'><%= link_to 'All Client Migrations', client_uploads_path %></li>

app/views/admins/nav/sidenavs/_roles.html.erb
<li id='new_role'><%= link_to 'New Admin Role', new_role_path %></li>
<% @roles.each do |role| %>
    <li id='role_<%= role.name.gsub(" ","_").downcase %>'><%= link_to role.name, role_path(id: role.id) %></a></li>
<% end %>

app/views/admins/nav/sidenavs/_sales_reps.html.erb
<li id='new_rep'><%= link_to 'New Sales Rep', new_rep_path %></li>
<li id='all_reps'><%= link_to 'All Sales Reps', search_reps_main_path %></li>
<li id='withdrawals'><%= link_to 'Withdrawal Requests', sales_payment_requests_path %></li>

app/views/admins/nav/sidenavs/_support.html.erb
<li id='home'><%= link_to 'Support Dashboard', admin_support_path %></li>
<li id='new_ticket'><%= link_to raw("Create Ticket"), admin_new_ticket_path %></li>
<li id='new_support'><%= link_to raw("New Tickets <span class='count'>#{SupportCase.where(status: 'Pending').count}</span>"), admin_new_tickets_path %></li>
<li id='priority_support'><%= link_to raw("Priority Tickets <span class='count'>#{SupportCase.where(status: 'Open', high_priority: true).count}</span>"), admin_priority_tickets_path %></li>
<li id='open'><%= link_to raw("Open Tickets <span class='count'>#{SupportCase.where(status: 'Open').count}</span>"), admin_open_tickets_path %></li>
<li id='closed'><%= link_to raw("Closed Tickets <span class='count'>#{SupportCase.where(status: 'Closed').count}</span>"), admin_closed_tickets_path %></li>
<li id='archived'><%= link_to 'Archive', admin_archived_tickets_path %></li>

app/views/admins/nav/sidenavs/_transactions.html.erb
<li id='index'><%= link_to 'Orders Dashboard', orders_path %></li>
<li id='new_tx'><%= link_to 'New Order', new_tx_path %></li>
<li id='pending_tx'><%= link_to raw("Pending Orders <span class='count'>#{Transaction.where(status: 'Pending').count}</span>"), pending_tx_path %></li>
<li id='paid_tx'><%= link_to raw("Paid Orders"), paid_tx_path %></li>
<li id='refunded_tx'><%= link_to raw("Refunded Orders"), refunded_tx_path %></li>
<li id='cancelled_tx'><%= link_to raw("Cancelled Orders"), cancelled_tx_path %></li>

app/views/admins/nav/sidenavs/_users.html.erb
<li id='new_user'><%= link_to 'New Client', new_user_path %></li>
<li id='all_users'><%= link_to 'All Clients', search_users_path %></li>

app/views/admins/nav/sidenavs/_users_individual.html.erb
<li id='user_profile'><%= link_to 'Client Details', view_user_path(id: @user.id) %></li>
<li id='user_tx'><%= link_to 'Payments & Subscriptions', view_user_transactions_path(id: @user.id) %></li>

app/views/admins/nav/sidenavs/_video.html.erb
<li id='channels_nav'><%= link_to 'Live Channels', live_channels_path %></li>
<li id='shows_nav'><%= link_to 'TV Shows', tv_shows_path %></li>
<li id='movies_nav'><%= link_to 'Movies', movies_path %></li>
<li id='home_grid'><%= link_to 'Homepage Grids', admin_home_grid_path %></li>
<li id='all_grid'><%= link_to 'All Grids', admin_all_grids_path %></li>
<li id='new_grid'><%= link_to 'New Grid', admin_new_grid_path %></li>
<li id='broken_links'><%= link_to 'Broken Links', admin_broken_links_path %></li>